tau = 2.
tempo = (4,4)
blanca = tau/2
negra = tau/4
corchea = tau/8
dotnegra = negra*1.5
himno = [["E4",blanca],
        ["F4",negra],
        ["G4",negra],
        ["G4",negra],
        ["F4",negra],
        ["E4",negra],
        ["D4",negra],
        ["C4",negra],
        ["C4",negra],
        ["D4",negra],
        ["E4",negra],
        ["E4",dotnegra],
        ["D4",corchea],
        ["D4",blanca], #
        ["E4",negra],
        ["E4",negra],
        ["F4",negra],
        ["G4",negra],
        ["G4",negra],
        ["F4",negra],
        ["E4",negra],
        ["D4",negra],
        ["C4",negra],
        ["C4",negra],
        ["D4",negra],
        ["E4",negra],
        ["D4",dotnegra],
        ["C4",corchea], 
        ["C4",blanca], #
        ["D4",blanca],
        ["E4",negra],
        ["C4",negra],
        ["D4",negra],
        ["E4",corchea],
        ["F4",corchea],
        ["E4",negra],
        ["C4",negra],
        ["D4",negra],
        ["E4",corchea],
        ["F4",corchea],
        ["E4",negra],
        ["D4",negra],
        ["C4",negra], 
        ["D4",negra],
        ["G4",blanca], #
        ["E4",negra],
        ["E4",negra],
        ["F4",negra],
        ["G4",negra],
        ["G4",negra],
        ["F4",negra],
        ["E4",negra],
        ["D4",negra],
        ["C4",negra],
        ["C4",negra],
        ["D4",negra],
        ["E4",negra],
        ["D4",dotnegra],
        ["C4",corchea],
        ["C4",blanca] #
]
